# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    - group: java-prod
  - name: maven-ops
    value: '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS'
  - name: PROJECT_ID
    value: 'maven-intro'

resources: 
  repositories:
  - repository: template-devops
    type: git
    name: jr-devops/template-java-mvn
    ref: refs/heads/main

extends:
  template: init.yml@template-devops